Ignore spurious ResourceWarning in tests when opening the rendered result in the browser on Linux
spyder-ide/docrepr pull request #35
Opened 2022-01-13 16:10 UTC by martinRenou

This prevents the tests from failing when running them with the `--open-browser` option. As discussed in https://github.com/spyder-ide/docrepr/pull/33#discussion_r772164817

2022-01-13 17:12 UTC, CAM-Gerlach requested changes
(Somehow, my first review didn't get picked up correctly, sorry)

2022-01-13 17:14 UTC, CAM-Gerlach requested changes
The issue with this very broad brush approach is it also silences any `ResourceWarning` anywhere in the code under test (or the test suite), and regardless of whether `--open-browser`` is passed. Instead, what I recommend you do is

> You can add the warnings filter to _open_browser in the open_browser fixture in conftest.py.

as this will ensure that it is only activated when it is needed (unless you can't get that to work, in which case there are still other less drastic options) Further, you should limit the filter to just the `subprocess` module (fourth field in the filter syntax, right after category).

Thanks!

Furthermore, I'd suggest limiting the filter to the `subprocess` module

2022-01-14 10:47 UTC, martinRenou commented
Thanks for the review.

> You can add the warnings filter to _open_browser in the open_browser fixture in conftest.py.

I fail to understand how this would look like? I tried multiple things, like:

```python
@pytest.fixture
def open_browser(request):
    """Show the passed URL in the user's web browser if passed."""
    def _open_browser(url):
        if request.config.getoption(OPEN_BROWSER_OPTION):
            pytestmark = pytest.mark.filterwarnings("ignore::ResourceWarning")

            webbrowser.open_new_tab(url)
    return _open_browser
```

Or 

```python
@pytest.fixture
def open_browser(request):
    """Show the passed URL in the user's web browser if passed."""
    @pytest.mark.filterwarnings("ignore::ResourceWarning")
    def _open_browser(url):
        if request.config.getoption(OPEN_BROWSER_OPTION):
            webbrowser.open_new_tab(url)
    return _open_browser
```

But that does not work. I didn't find any documentation about filtering warnings on pytest fixtures, it seems to only be documented for test cases.

2022-01-14 23:29 UTC, CAM-Gerlach commented
Sorry, I meant just using the normal `warnings.filterwarnings`, i.e.

```
@pytest.fixture
def open_browser(request):
    """Show the passed URL in the user's web browser if passed."""
    def _open_browser(url):
        if request.config.getoption(OPEN_BROWSER_OPTION):
            warnings.filterwarnings(
                'ignore', category=ResourceWarning, module='subprocess.*')
            webbrowser.open_new_tab(url)
    return _open_browser
```

(You might need to play around with the `module` option; if you can't get it to work at all, you can elide it if nessesary)

This ensures it works regardless of where/what scope the warning fires at (which can be tricky due to relating to non-deterministic, OS-specific source/destructor behavior, as suggested by the nature of the warning and the traceback), and gets applied immediately before opening the browser, if and only if the browser is to be opened (and without having to add it directly to any test code that uses it).

2022-01-17 08:51 UTC, martinRenou commented
Oh I see, thanks!

I updated the PR

2022-01-17 09:07 UTC, CAM-Gerlach approved these changes
LGTM, thanks @martinRenou !

2022-01-17 09:08 UTC, merged